language: node_js
sudo: true
node_js:
- stable
script:
- npm test
env:
  global:
  - CF_APP=tone-analyzer-demo-jz
  - CF_API=https://api.ng.bluemix.net
  - CF_ORGANIZATION=jzhang300@us.ibm.com
  - CF_SPACE=dev
  - secure: "r0i8rdTSaNtIHyCo0znfZHTr6WnrCUbHPbe2G6A4lMbRdRBGQhJ7Z75egf9UOrim5eM5JtAEUUwjntNPzciqnuuWn5IhNGf8F5pwXgDmeLa+H9yWy7oaVHSfTnQiDZrHAybkNu5wkkFjO05Z3QOS3Ji4DmWT+xg97TItpNLF+U+wITLQccQkM8MfOO889w5S3/CQBO8Oei/i8FO5Nfj90Jq+FkOtt1EGiZLBPeV9/N0BOIFGYQJvhRYcrpseCp6v1ufMtA7r66P0fHK7neocZ5utMu510Yx7ARmnfx4USelT9t2FMjvJO4nod9jDWdxERkP7xFQE4G26qeSSWCa0kPIty8KhKz1C7R7q+rQpi/UnPP+WO7G9dsNU6AFlf4Nz1Ppbd1CyhKc9sUUXQTwWO5FfF4nKlpF/6vXG5Xieo+1emsCHab2pVg2ESOYh9MaSJ/Z7wiD96/GSA8sN3BuHBDyQ8dWJQQpc3iRoH1BB5iC5/N6/ekqC7vXpwBkCQ6no1YSmZ16kUmrtaXe5BsvDjO2Sq6rJbQ51/suyuGC0iTT5602/k387uSDHRN4dKtB79dR8p11XFoeZyYdNjHzu8n9Gl8OgPG0cGQh+hG+h9jj64xVwIlLYjCjjWN/zanVsoZUcOCSogRDxagoqSn8D8Ag9uRKZtS/O+FAVmDvDaDM="
  - secure: "U1bAykldpCx75oaqd/mNUBoY3K7KBKu+hVd7hHSfJDlx8mN5mWu2abZmtW8jpMLKvA7geQTUGPJvbL35AZZE2hvswCt4txyAVXK13QiymJg0fttU+10v4Tc11KVikko/MoLeIfPe09s75PdJ90rzqlSeKFiPol241Pvq+OZydlUGEH/tthzATr9vUJpRvY3no/R1Vt2SwdSRY5/M7L4qDkD3BO+t6glH/T60QvL6Yz4GCkmsvgb3LYzuRAaFFJbmSTIwLov6lX3dlb0aABhP5P7VkzEueeXPq6KIauoc3uFaD0aQeoxq2k1Qol5j0/FegxnxXPElJrqD4T8aRdOnU6OX3Q4EwhRARd2naQUDH4cShPlwvw1mq0EL4ViJgUW46bjmXUJhoj29vf0dUwIEGDXIQeMjTNlAN5BLAgeojPnkX7iN1lEZ6Gfoam02ntL1R563ffOQQ8pD7bjl+N1Y4pDPnZKGXh6mRM8Dbr4SNs91QVLhLNldEWq2Dvkg5NZEITEwrkRd2Ec75pzBs9UDg8lmu4k7WxLPh+hW/Sso1jNdg7g83pVzaXwYcjm+TqCFfsrcV4NOpXUTHOsgygQ41UGn/V6+s9nqudqlPSyw7E8jQjXEKiIkidxn/INMonLAYNOOHf2PRMJxd8WF/2+UtOHbOpGhMCTAIlHD0KWTk4g="
before_deploy: npm install -g cf-blue-green
deploy:
  provider: script
  script:
    - cf-blue-green-travis
  on:
    branch: master
    repo: watson-developer-cloud/tone-analyzer-nodejs
  skip_cleanup: true
notifications:
  email: false
